COL SORT1 NOPRINT 
COL SORT2 NOPRINT 
COL SORT3 NOPRINT 
COL SORT4 NOPRINT 
BREAK ON SORT2 SKIP 1
set linesize 120
SET HEADING OFF
SET ECHO OFF
SET FEEDBACK OFF
SET PAGESIZE 0
SPOOL bldpkcn.sql

select 'set echo on ' from dual;
select 'spool bldpkcn.lst' from dual;
select 'Remark Build Primary Key constraints' from dual;

SELECT TABLE_NAME SORT1, CONSTRAINT_NAME SORT2, 1 SORT3, 0 SORT4,
'ALTER TABLE '|| TABLE_NAME
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE IN ('P','U')
UNION
SELECT TABLE_NAME SORT1, CONSTRAINT_NAME SORT2, 1 SORT3, 1 SORT4,
' ADD ( CONSTRAINT ' || CONSTRAINT_NAME ||
decode (constraint_type,'P',' PRIMARY KEY (','U',' UNIQUE (',' NONE')
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE IN ('P','U')
UNION
SELECT UC.TABLE_NAME SORT1, UC.CONSTRAINT_NAME SORT2, 2 SORT3,
POSITION SORT4, ' '||COLUMN_NAME
FROM USER_CONS_COLUMNS UCC, USER_CONSTRAINTS UC
WHERE UCC.TABLE_NAME = UC.TABLE_NAME
AND UCC.CONSTRAINT_NAME = UC.CONSTRAINT_NAME
AND CONSTRAINT_TYPE IN ('P','U')
AND POSITION = 1
UNION
SELECT UC.TABLE_NAME SORT1, UC.CONSTRAINT_NAME SORT2, 3 SORT3,
POSITION SORT4, ' ,'||COLUMN_NAME
FROM USER_CONS_COLUMNS UCC, USER_CONSTRAINTS UC
WHERE UCC.TABLE_NAME = UC.TABLE_NAME
AND UCC.CONSTRAINT_NAME = UC.CONSTRAINT_NAME
AND UC.CONSTRAINT_TYPE IN ('P','U')
AND POSITION <> 1
UNION
SELECT UI.TABLE_NAME SORT1, UC.CONSTRAINT_NAME SORT2, 5 SORT3, 0 SORT4,
' ) USING INDEX TABLESPACE ' || UI.TABLESPACE_NAME ||
' PCTFREE ' || UI.PCT_FREE
FROM USER_INDEXES UI, USER_CONSTRAINTS UC
WHERE UC.CONSTRAINT_TYPE IN ('P','U')
AND UC.CONSTRAINT_NAME = UI.INDEX_NAME
UNION
SELECT UI.TABLE_NAME SORT1, UC.CONSTRAINT_NAME SORT2, 6 SORT3, 0 SORT4,
' STORAGE ( INITIAL ' || UI.INITIAL_EXTENT || ' NEXT ' ||
UI.NEXT_EXTENT || ' PCTINCREASE ' || UI.PCT_INCREASE || ' ));'
FROM USER_INDEXES UI, USER_CONSTRAINTS UC
WHERE UC.CONSTRAINT_TYPE IN ('P','U')
AND UC.CONSTRAINT_NAME = UI.INDEX_NAME
ORDER BY 1, 2, 3, 4;
