SELECT DS.TABLESPACE_NAME, SEGMENT_NAME, ROUND(SUM(DS.BYTES) / (1024 * 1024)) AS MB
  FROM DBA_SEGMENTS DS
  WHERE  DS.SEGMENT_NAME in  ('ADDRESS', 'PPCEXTDATA', 'USERDEMO', 'USERREG', 'XPRESCRIPTION' ) and DS.OWNER = 'IN'
GROUP BY DS.TABLESPACE_NAME,
       SEGMENT_NAME;
       
       
