/**********************************************************************
       Copyright ESA Software SpA. Via Draghi, 39 RIMINI
 **********************************************************************
 *** Modulo	  : AMBIENTE
 *** RDBMS	  : Oracle
 *** Data         : 05/10/98	
 *** Autore       : Stefano Teodorani
 *** Descrizione  : Modifica lo user di un db importato da una sorgente 
 ***                con nome diverso
 **********************************************************************/

-- da eseguire sol societario
ALTER TABLE MGXX_MODULOUTE DISABLE CONSTRAINT MGXX_MODULOUTE_F2;
ALTER TABLE MGXX_CONTRSTDOC DISABLE CONSTRAINT MGXX_CONTRSTDOC_F1;
ALTER TABLE MGXX_CONTRSTDOC DISABLE CONSTRAINT MGXX_CONTRSTDOC_F2;
ALTER TABLE CCXX_CONTRSTUTE DISABLE CONSTRAINT CCXX_CONTRSTUTE_F2;
ALTER TABLE CCXX_CONTUTERIGA DISABLE CONSTRAINT CCXX_CONTUTERIGA_F2;
ALTER TABLE CLXX_PAR_UTE disable constraint CLXX_PAR_UTE_F2;
ALTER TABLE DBXX_PAR_UTE disable constraint DBXX_PAR_UTE_F2;
ALTER TABLE PRXX_ST_MODUTE disable constraint PRXX_ST_MODUTE_F2;


-- da eseguire sol sovrasocietario
ACCEPT NUOVO_UTENTE CHAR PROMPT 'NUOVO UTENTE: '
ACCEPT VECCHIO_UTENTE CHAR PROMPT 'VECCHIO UTENTE: '

ALTER TABLE TSUM_SOCIETA DISABLE CONSTRAINT TSUM_SOCIETA_F1;
ALTER TABLE TSUM_SOCIETA DISABLE CONSTRAINT TSUM_SOCIETA_F2;
ALTER TABLE TSUM_UTEAPPLSOC DISABLE CONSTRAINT TSUM_UTEAPPLSOC_F1;
ALTER TABLE TSUM_UTEAPPLSOC DISABLE CONSTRAINT TSUM_UTEAPPLSOC_F2;
ALTER TABLE TSUM_UTEAPPLSOC DISABLE CONSTRAINT TSUM_UTEAPPLSOC_F3;
ALTER TABLE TSUM_UTEAPPLSOCRUO DISABLE CONSTRAINT TSUM_UTEAPPLSOCRUO_F1;
ALTER TABLE TSUM_UTEAPPLSOCRUO DISABLE CONSTRAINT TSUM_UTEAPPLSOCRUO_F2;


UPDATE TSUM_UTENTEDB
SET CDA_UTE_DB = '&NUOVO_UTENTE',
    DES_PWD_DB = '&NUOVO_UTENTE'
WHERE CDA_UTE_DB = '&VECCHIO_UTENTE'
/

UPDATE TSUM_SOCIETA
SET CDA_UTE_DB = '&NUOVO_UTENTE'
WHERE CDA_UTE_DB = '&VECCHIO_UTENTE'
/

UPDATE TSUM_UTEAPPLSOC
SET CDA_UTE_APPL = '&NUOVO_UTENTE',
    CDA_UTE_DB = '&NUOVO_UTENTE'
WHERE CDA_UTE_DB = '&VECCHIO_UTENTE'
/

UPDATE TSUM_UTENTEAPPL
SET CDA_UTE_APPL = '&NUOVO_UTENTE',
    DES_PWD_APPL = '&NUOVO_UTENTE'
WHERE CDA_UTE_APPL = '&VECCHIO_UTENTE'
/

update TSUM_UTEAPPLSOCRUO
SET CDA_UTE_APPL = '&NUOVO_UTENTE'
WHERE CDA_UTE_APPL = '&VECCHIO_UTENTE'
/


ALTER TABLE TSUM_SOCIETA ENABLE CONSTRAINT TSUM_SOCIETA_F1;
ALTER TABLE TSUM_SOCIETA ENABLE CONSTRAINT TSUM_SOCIETA_F2;
ALTER TABLE TSUM_UTEAPPLSOC ENABLE CONSTRAINT TSUM_UTEAPPLSOC_F1;
ALTER TABLE TSUM_UTEAPPLSOC ENABLE CONSTRAINT TSUM_UTEAPPLSOC_F2;
ALTER TABLE TSUM_UTEAPPLSOC ENABLE CONSTRAINT TSUM_UTEAPPLSOC_F3;
ALTER TABLE TSUM_UTEAPPLSOCRUO ENABLE CONSTRAINT TSUM_UTEAPPLSOCRUO_F1;
ALTER TABLE TSUM_UTEAPPLSOCRUO ENABLE CONSTRAINT TSUM_UTEAPPLSOCRUO_F2;


PAUSE FERMARE QUI ESECUZIONE
-- SUL societario eseguire i seguenti update


UPDATE  MGXX_MODULOUTE
SET 	CDA_UTE_APPL = '&NUOVO_UTENTE'
WHERE 	CDA_UTE_APPL = '&VECCHIO_UTENTE'
/

UPDATE  CCXX_CONTRSTUTE
SET 	CDA_UTE_APPL = '&NUOVO_UTENTE'
WHERE 	CDA_UTE_APPL = '&VECCHIO_UTENTE'
/

UPDATE  MGXX_CONTRSTDOC
SET 	CDA_UTE_APPL = '&NUOVO_UTENTE'  
WHERE 	CDA_UTE_APPL = '&VECCHIO_UTENTE'
/ 

ALTER TABLE MGXX_MODULOUTE ENABLE CONSTRAINT MGXX_MODULOUTE_F2;
ALTER TABLE MGXX_CONTRSTDOC ENABLE CONSTRAINT MGXX_CONTRSTDOC_F1;
ALTER TABLE MGXX_CONTRSTDOC ENABLE CONSTRAINT MGXX_CONTRSTDOC_F2;
ALTER TABLE CCXX_CONTRSTUTE ENABLE CONSTRAINT CCXX_CONTRSTUTE_F2;
ALTER TABLE CCXX_CONTUTERIGA ENABLE CONSTRAINT CCXX_CONTUTERIGA_F2;
ALTER TABLE CLXX_PAR_UTE enable constraint CLXX_PAR_UTE_F2;
ALTER TABLE DBXX_PAR_UTE enable constraint DBXX_PAR_UTE_F2;
ALTER TABLE PRXX_ST_MODUTE enable constraint PRXX_ST_MODUTE_F2;